[tool.poetry]
name = "django-channel"
version = "0.1.0"
description = ""
authors = ["Sourav"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
